apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels: # deployment related labels
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
     component: mysql
     project: expense
     tier: db
  template: #pod definition
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0
        # ports:
        # - containerPort: 3306
